model:
  base_learning_rate: 6e-5
  target: ldm.models.embedding.XrayEmbedding

  params:
    n_embed: 8192
    embed_dim: 8
    image_key: "xray"
    label_key: "image"
    monitor: val/rec_loss

    ddconfig:
      ch: 128
      resolution: 128
      attn_resolutions: [8]
      ch_mult: [1,2,4]    # num_down = len(ch_mult)-1
      num_blocks: 2
      z_channels: 16
      attn_type: "vanilla"    # to be continued
      dropout: 0.0
      num_groups: 32

data:
  batch_size: 8
  base_dir: /home/first/XctDiff/dataset
  json_list: ["json/LIDC_IDRI.json"]
  num_workers: 16
  pin_memory: True
